### PR TITLE
feat(perception): enable to specify `region` filter.

### PR DESCRIPTION
**Pull request by MasatoSaeki**
## Types of PR

- [x] New Features
- [ ] Upgrade of existing features
- [ ] Bugfix

## Description
This PR enables to specify `region` based on x-y coordinate from ego, and you can still use `distance` filter.

### Interface roles
1. You can only specify `Distance` or `Region`
2. Specification role is that `lower_limit` and `upper_limit` are combined by `,` while `Distance` is combined by `-`.
3. You must specify `lower_limit` and `upper_limit` of `x_position` or `y_position` if use `Region`.

## How to review this PR
Fundamentally, follow [this docs](https://github.com/tier4/driving_log_replayer_v2/blob/develop/docs/quick_start/setup.ja.md)
assume that you have already done build of Autoware. To use branch is below.
- driving_log_replayer_v2 -> `feat/limitation_by_area`
- perception_eval -> `feat/limitation_by_area`
```
mkdir -p ~/driving_log_replayer_v2
gdown -O ~/driving_log_replayer_v2/sample_dataset_v2.tar.zst 'https://docs.google.com/uc?export=download&id=1iCoykBBETI_rGfKEFYYb7LFydF-RJVkC'
tar -I zstd -xvf ~/driving_log_replayer_v2/sample_dataset_v2.tar.zst -C ~/driving_log_replayer_v2/
gdown -O ~/driving_log_replayer_v2/sample-map-planning.zip 'https://docs.google.com/uc?export=download&id=1499_nsbUbIeturZaDj7jhUownh5fvXHd'
unzip -d ~/driving_log_replayer_v2/ ~/driving_log_replayer_v2/sample-map-planning.zip
mv ~/driving_log_replayer_v2/sample-map-planning ~/driving_log_replayer_v2/sample_dataset/map
```
```
SAMPLE_ROOT=${path/to/autoware}/src/simulator/driving_log_replayer_v2/sample
cp ${SAMPLE_ROOT}/perception/scenario.yaml ~/driving_log_replayer_v2/perception.yaml
```
```
source install setup.bash
 ros2 launch driving_log_replayer_v2 driving_log_replayer_v2.launch.py scenario_path:=$HOME/driving_log_replayer_v2/perception.yaml dataset_index:=0 sensing:=false
```

You can specify `region` like below
```
Filter:
  Distance: null # [m] null [Do not filter by distance] or lower_limit-(upper_limit) [Upper limit can be omitted. If omitted value is 1.7976931348623157e+308]
  Region:
    x_position: -10,10 # [m] null [Do not filter by x_position] or lower_limit,upper_limit [Upper limit can be omitted. If omitted value is 1.7976931348623157e+308]
    y_position: 0,20 # [m] null [Do not filter by y_position] or lower_limit,upper_limit [Upper limit can be omitted. If omitted value is 1.7976931348623157e+308]
```
## Others
- https://github.com/tier4/autoware_perception_evaluation/pull/200

### CODE REVIEW

**Review by hayato-m126 — CHANGES_REQUESTED** [review]
Since the distance from the center is always positive, it is possible to get the lower upper by splitting a string like 0.0-18.0 with -.

But with postion, aren't there also negative values?
For example, if it is -1.0-18.0, it is difficult to handle because there are multiple hyphens.

Other than that, I didn't see anything else that bothered me.

**Review by hayato-m126 — DISMISSED** [review]
> Specification role is that lower_limit and upper_limit are combined by , while Distance is combined by -.

I had missed it.

**Comment by MasatoSaeki** [comment]
@hayato-m126 
I change traffic light code in order to adopt this PR (I have checked this PR on my local pc). https://github.com/tier4/driving_log_replayer_v2/pull/68/commits/718d0882137087f0860cebf50345c27e8edd0518

And, I wait for releasing autoware_perception_evaluation which [related PR](https://github.com/tier4/autoware_perception_evaluation/pull/200)

**Comment by hayato-m126** [comment]
The reason why colcon test is failing is because the main branch of perception_eval does not contain the update corresponding to this PR.
If you test on hand with the same version, it passes.

**Review by hayato-m126 — APPROVED** [review]
LGTM

**Pull request merged**
